name = "public-capitalism-hub"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "public-capitalism-applications"
database_id = "5e53d365-8695-4f78-9aa0-a099fb31a041"
